<?php

return array(
	array('id' => '1','faction' => 'cygnar','name' => 'Captain Allister Caine','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '2','faction' => 'protectorate-of-menoth','name' => 'Feora, Protector of the Flame','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '3','faction' => 'khador','name' => 'Forward Kommander Sorscha','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '4','faction' => 'cygnar','name' => 'General Adept Nemo','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '5','faction' => 'cryx','name' => 'Goreshade the Cursed','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '6','faction' => 'protectorate-of-menoth','name' => 'Grand Exemplar Kreoss','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '7','faction' => 'protectorate-of-menoth','name' => 'Hierarch Severius','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '8','faction' => 'khador','name' => 'Kommander Orsus Zoktavir','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '9','faction' => 'cryx','name' => 'Lich Lord Asphyxious','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '10','faction' => 'cygnar','name' => 'Lord Commander Stryker','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '12','faction' => 'cygnar','name' => 'Major Victoria Haley','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '13','faction' => 'cryx','name' => 'Skarre, Queen of the Broken Coast','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '14','faction' => 'khador','name' => 'Supreme Kommandant Irusk','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '15','faction' => 'protectorate-of-menoth','name' => 'Testament of Menoth','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '16','faction' => 'khador','name' => 'Vladimir Tzepesci, the Dark Champion','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '17','faction' => 'cryx','name' => 'Wraith Witch Deneghra','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '18','faction' => 'mercenaries','name' => 'Ashlynn D\'Elyse','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '19','faction' => 'mercenaries','name' => 'Captain Bartolo Montador','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '20','faction' => 'cygnar','name' => 'Captain E.Dominic Darius','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '21','faction' => 'cygnar','name' => 'Captain Jeremiah Kraye','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '22','faction' => 'mercenaries','name' => 'Captain Phinneus Shae','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '23','faction' => 'cygnar','name' => 'Captain Victoria Haley','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '24','faction' => 'cygnar','name' => 'Commander Adept Nemo','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '25','faction' => 'cygnar','name' => 'Commander Coleman Stryker','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '26','faction' => 'mercenaries','name' => 'Durgen Madhammer','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '27','faction' => 'protectorate-of-menoth','name' => 'Feora, Priestress of the Flame','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '28','faction' => 'mercenaries','name' => 'Fiona the Black','type' => 'casterlock','number' => '1','cost' => '-7','field_allowance' => 'C','parent' => ''),
	array('id' => '29','faction' => 'cryx','name' => 'Goreshade the Bastard','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '30','faction' => 'mercenaries','name' => 'Gorten Grundback','type' => 'casterlock','number' => '1','cost' => '-7','field_allowance' => 'C','parent' => ''),
	array('id' => '31','faction' => 'protectorate-of-menoth','name' => 'Grand Scrutator Severius','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '32','faction' => 'protectorate-of-menoth','name' => 'High Allegiant Amon Ad-Raza','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '33','faction' => 'protectorate-of-menoth','name' => 'High Executioner Servath Reznik','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '34','faction' => 'protectorate-of-menoth','name' => 'High Exemplar Kreoss','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '35','faction' => 'cryx','name' => 'Iron Lich Asphyxious','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '36','faction' => 'khador','name' => 'Karchev the Terrible','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '37','faction' => 'khador','name' => 'Koldun Kommander Aleksandra Zerkova','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '38','faction' => 'khador','name' => 'Kommandant Irusk','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '39','faction' => 'khador','name' => 'Kommander Sorsha','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '40','faction' => 'cryx','name' => 'Lich Lord Terminus','type' => 'casterlock','number' => '1','cost' => '-4','field_allowance' => 'C','parent' => ''),
	array('id' => '41','faction' => 'cygnar','name' => 'Lieutenant Allister Caine','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '42','faction' => 'mercenaries','name' => 'Magnus the Traitor','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '43','faction' => 'cygnar','name' => 'Major Markus \'Siege\' Brisebane','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '44','faction' => 'cryx','name' => 'Master Necrotech Mortenebra & Deryliss','type' => 'casterlock','number' => '1','cost' => '-4','field_allowance' => 'C','parent' => '44'),
	array('id' => '45','faction' => 'cryx','name' => 'Pirate Queen Skarre','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '46','faction' => 'khador','name' => 'The Butcher of Khardov','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '47','faction' => 'protectorate-of-menoth','name' => 'The Harbinger of Menoth','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '48','faction' => 'protectorate-of-menoth','name' => 'The High Reclaimer','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '49','faction' => 'cryx','name' => 'The Witch Coven of Garlghast','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '50','faction' => 'khador','name' => 'Vladimir, the Dark Prince','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '51','faction' => 'cryx','name' => 'Warwitch Deneghra','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '52','faction' => 'khador','name' => 'Zevanna Agha, The Old Witch of Khador','type' => 'casterlock','number' => '1','cost' => '-3','field_allowance' => 'C','parent' => ''),
	array('id' => '53','faction' => 'protectorate-of-menoth','name' => 'Avatar of Menoth','type' => 'jackbeast','number' => '1','cost' => '11','field_allowance' => 'C','parent' => ''),
	array('id' => '54','faction' => 'khador','name' => 'Beast-09','type' => 'jackbeast','number' => '1','cost' => '11','field_allowance' => 'C','parent' => ''),
	array('id' => '55','faction' => 'khador','name' => 'Behemoth','type' => 'jackbeast','number' => '1','cost' => '13','field_allowance' => 'C','parent' => ''),
	array('id' => '56','faction' => 'khador','name' => 'Berserker','type' => 'jackbeast','number' => '1','cost' => '6','field_allowance' => 'U','parent' => ''),
	array('id' => '57','faction' => 'protectorate-of-menoth','name' => 'Castigator','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'U','parent' => ''),
	array('id' => '58','faction' => 'cygnar','name' => 'Centurion','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '59','faction' => 'protectorate-of-menoth','name' => 'Crusader','type' => 'jackbeast','number' => '1','cost' => '6','field_allowance' => 'U','parent' => ''),
	array('id' => '60','faction' => 'cryx','name' => 'Deathjack','type' => 'jackbeast','number' => '1','cost' => '12','field_allowance' => 'C','parent' => ''),
	array('id' => '61','faction' => 'cygnar','name' => 'Defender','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '62','faction' => 'khador','name' => 'Destroyer','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '63','faction' => 'khador','name' => 'Devastator','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '64','faction' => 'khador','name' => 'Drago','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'C','parent' => ''),
	array('id' => '65','faction' => 'protectorate-of-menoth','name' => 'Fire of Salvation','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'C','parent' => ''),
	array('id' => '66','faction' => 'mercenaries','name' => 'Freebooter','type' => 'jackbeast','number' => '1','cost' => '6','field_allowance' => 'U','parent' => ''),
	array('id' => '67','faction' => 'mercenaries','name' => 'Ghordson Driller','type' => 'jackbeast','number' => '1','cost' => '6','field_allowance' => 'U','parent' => ''),
	array('id' => '68','faction' => 'protectorate-of-menoth','name' => 'Guardian','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '69','faction' => 'cygnar','name' => 'Hammersmith','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'U','parent' => ''),
	array('id' => '70','faction' => 'cryx','name' => 'Harrower','type' => 'jackbeast','number' => '1','cost' => '10','field_allowance' => 'U','parent' => ''),
	array('id' => '71','faction' => 'cygnar','name' => 'Ironclad','type' => 'jackbeast','number' => '1','cost' => '7','field_allowance' => 'U','parent' => ''),
	array('id' => '72','faction' => 'khador','name' => 'Juggernaut','type' => 'jackbeast','number' => '1','cost' => '7','field_allowance' => 'U','parent' => ''),
	array('id' => '73','faction' => 'khador','name' => 'Kodiak','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'U','parent' => ''),
	array('id' => '74','faction' => 'cryx','name' => 'Leviathan','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '75','faction' => 'mercenaries','name' => 'Mangler','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'U','parent' => ''),
	array('id' => '76','faction' => 'khador','name' => 'Marauder','type' => 'jackbeast','number' => '1','cost' => '7','field_allowance' => 'U','parent' => ''),
	array('id' => '77','faction' => 'mercenaries','name' => 'Mariner','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'U','parent' => ''),
	array('id' => '78','faction' => 'mercenaries','name' => 'Mule','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'U','parent' => ''),
	array('id' => '79','faction' => 'cryx','name' => 'Nightmare','type' => 'jackbeast','number' => '1','cost' => '10','field_allowance' => 'C','parent' => ''),
	array('id' => '80','faction' => 'mercenaries','name' => 'Nomad','type' => 'jackbeast','number' => '1','cost' => '6','field_allowance' => 'U','parent' => ''),
	array('id' => '81','faction' => 'cygnar','name' => 'Ol\'Rowdy','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'C','parent' => ''),
	array('id' => '82','faction' => 'cryx','name' => 'Reaper','type' => 'jackbeast','number' => '1','cost' => '7','field_allowance' => 'U','parent' => ''),
	array('id' => '83','faction' => 'protectorate-of-menoth','name' => 'Reckoner','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'U','parent' => ''),
	array('id' => '84','faction' => 'cryx','name' => 'Seether','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '85','faction' => 'cryx','name' => 'Slayer','type' => 'jackbeast','number' => '1','cost' => '6','field_allowance' => 'U','parent' => ''),
	array('id' => '86','faction' => 'khador','name' => 'Spriggan','type' => 'jackbeast','number' => '1','cost' => '10','field_allowance' => 'U','parent' => ''),
	array('id' => '87','faction' => 'cygnar','name' => 'Stormclad','type' => 'jackbeast','number' => '1','cost' => '10','field_allowance' => 'U','parent' => ''),
	array('id' => '88','faction' => 'cygnar','name' => 'Thunderhead','type' => 'jackbeast','number' => '1','cost' => '12','field_allowance' => 'C','parent' => ''),
	array('id' => '89','faction' => 'protectorate-of-menoth','name' => 'Vanquisher','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'U','parent' => ''),
	array('id' => '90','faction' => 'mercenaries','name' => 'Wroughthammer Rockram','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'U','parent' => ''),
	array('id' => '91','faction' => 'protectorate-of-menoth','name' => 'Blessing of Vengeance','type' => 'jackbeast','number' => '1','cost' => '7','field_allowance' => 'C','parent' => ''),
	array('id' => '92','faction' => 'mercenaries','name' => 'Buccaneer','type' => 'jackbeast','number' => '1','cost' => '3','field_allowance' => 'U','parent' => ''),
	array('id' => '93','faction' => 'cryx','name' => 'Cankerworm','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'C','parent' => ''),
	array('id' => '94','faction' => 'cygnar','name' => 'Charger','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '95','faction' => 'cryx','name' => 'Deathripper','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '96','faction' => 'cryx','name' => 'Defiler','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '97','faction' => 'protectorate-of-menoth','name' => 'Dervish','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '98','faction' => 'protectorate-of-menoth','name' => 'Devout','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '99','faction' => 'cygnar','name' => 'Grenadier','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '100','faction' => 'mercenaries','name' => 'Grunback Blaster','type' => 'jackbeast','number' => '1','cost' => '3','field_allowance' => 'U','parent' => ''),
	array('id' => '101','faction' => 'mercenaries','name' => 'Grunback Gunner','type' => 'jackbeast','number' => '1','cost' => '3','field_allowance' => 'U','parent' => ''),
	array('id' => '102','faction' => 'cryx','name' => 'Helldiver','type' => 'jackbeast','number' => '1','cost' => '3','field_allowance' => 'U','parent' => ''),
	array('id' => '103','faction' => 'cygnar','name' => 'Hunter','type' => 'jackbeast','number' => '1','cost' => '6','field_allowance' => 'U','parent' => ''),
	array('id' => '104','faction' => 'cygnar','name' => 'Lancer','type' => 'jackbeast','number' => '1','cost' => '6','field_allowance' => 'U','parent' => ''),
	array('id' => '105','faction' => 'cryx','name' => 'Nightwretch','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '106','faction' => 'protectorate-of-menoth','name' => 'Redeemer','type' => 'jackbeast','number' => '1','cost' => '6','field_allowance' => 'U','parent' => ''),
	array('id' => '107','faction' => 'mercenaries','name' => 'Renegade','type' => 'jackbeast','number' => '1','cost' => '6','field_allowance' => '2','parent' => ''),
	array('id' => '108','faction' => 'protectorate-of-menoth','name' => 'Repenter','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '109','faction' => 'protectorate-of-menoth','name' => 'Revenger','type' => 'jackbeast','number' => '1','cost' => '6','field_allowance' => 'U','parent' => ''),
	array('id' => '110','faction' => 'cygnar','name' => 'Sentinel','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '111','faction' => 'cryx','name' => 'Stalker','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '112','faction' => 'mercenaries','name' => 'Talon','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '113','faction' => 'cygnar','name' => 'Thorn','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'C','parent' => ''),
	array('id' => '114','faction' => 'mercenaries','name' => 'Vanguard','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '115','faction' => 'protectorate-of-menoth','name' => 'Allegiant of the Order of the Fist','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '116','faction' => 'mercenaries','name' => 'Anastasia Dibray','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'U','parent' => ''),
	array('id' => '117','faction' => 'cryx','name' => 'Bane Lord Tartarus','type' => 'warrior','number' => '1','cost' => '4','field_allowance' => 'C','parent' => ''),
	array('id' => '118','faction' => 'cryx','name' => 'Bloat Thrall','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '119','faction' => 'mercenaries','name' => 'Bloody Bradigan','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'U','parent' => ''),
	array('id' => '120','faction' => 'cygnar','name' => 'Captain Arlan Strangewayes','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'C','parent' => ''),
	array('id' => '121','faction' => 'cygnar','name' => 'Captain Maxwell Finn','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => 'C','parent' => ''),
	array('id' => '122','faction' => 'cryx','name' => 'Captain Rengrave','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'C','parent' => ''),
	array('id' => '123','faction' => 'cryx','name' => 'Dargath Wrathe','type' => 'warrior','number' => '1','cost' => '4','field_allowance' => 'C','parent' => ''),
	array('id' => '124','faction' => 'retribution-of-scyrah','name' => 'Eyriss, Angel of Retribution','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => 'C','parent' => ''),
	array('id' => '125','faction' => 'retribution-of-scyrah','name' => 'Eyriss, Mage Hunter of Ios','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => 'C','parent' => ''),
	array('id' => '126','faction' => 'khador','name' => 'Fenris','type' => 'warrior','number' => '1','cost' => '5','field_allowance' => 'C','parent' => ''),
	array('id' => '127','faction' => 'cryx','name' => 'General Gerlak Slaughterborn','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '1','parent' => ''),
	array('id' => '128','faction' => 'mercenaries','name' => 'Goremand di Wulfe, Rogue Alchemist','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'U','parent' => ''),
	array('id' => '129','faction' => 'cygnar','name' => 'Gun Mage Captain Adept','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '130','faction' => 'protectorate-of-menoth','name' => 'Hierophant','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => ''),
	array('id' => '131','faction' => 'protectorate-of-menoth','name' => 'High Exemplar Gravius','type' => 'warrior','number' => '1','cost' => '5','field_allowance' => 'C','parent' => ''),
	array('id' => '132','faction' => 'protectorate-of-menoth','name' => 'High Paladin Dartan Vilmon','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => 'C','parent' => ''),
	array('id' => '133','faction' => 'cygnar','name' => 'Journeyman Warcaster','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '1','parent' => ''),
	array('id' => '134','faction' => 'mercenaries','name' => 'Kell Bailoch','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'U','parent' => ''),
	array('id' => '135','faction' => 'protectorate-of-menoth','name' => 'Knights Exemplar Seneschal','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '136','faction' => 'khador','name' => 'Koldun Lord','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => ''),
	array('id' => '137','faction' => 'khador','name' => 'Kovnik Jozef Grigorovich','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'C','parent' => ''),
	array('id' => '138','faction' => 'khador','name' => 'Kovnik Markov','type' => 'warrior','number' => '1','cost' => '4','field_allowance' => 'C','parent' => ''),
	array('id' => '139','faction' => 'mercenaries','name' => 'Lord Rockbottom','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'U','parent' => ''),
	array('id' => '140','faction' => 'cryx','name' => 'Machine Wraith','type' => 'warrior','number' => '1','cost' => '1','field_allowance' => '3','parent' => ''),
	array('id' => '141','faction' => 'cygnar','name' => 'Major Katherine Laddermore','type' => 'warrior','number' => '1','cost' => '5','field_allowance' => 'C','parent' => ''),
	array('id' => '142','faction' => 'khador','name' => 'Man-O-War Drakhun','type' => 'warrior','number' => '1','cost' => '4','field_allowance' => '1','parent' => ''),
	array('id' => '143','faction' => 'khador','name' => 'Man-O-War Drakhun (dismount)','type' => 'warrior','number' => '1','cost' => '5','field_allowance' => '1','parent' => ''),
	array('id' => '144','faction' => 'khador','name' => 'Man-O-War Kovnik','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '145','faction' => 'khador','name' => 'Manhunter','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '146','faction' => 'mercenaries','name' => 'Master Gunner Dougal Macnaile','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => 'U','parent' => ''),
	array('id' => '147','faction' => 'cryx','name' => 'Necrotech & Scrap Thralls','type' => 'warrior','number' => '1','cost' => '1','field_allowance' => '3','parent' => ''),
	array('id' => '148','faction' => 'mercenaries','name' => 'Ogrun Bokur','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => 'U','parent' => ''),
	array('id' => '149','faction' => 'mercenaries','name' => 'Orn Midwinter, Rogue Inquisitor','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'U','parent' => ''),
	array('id' => '150','faction' => 'protectorate-of-menoth','name' => 'Paladin of the Order of the Wall','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '151','faction' => 'cryx','name' => 'Pistol Wraith','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '152','faction' => 'protectorate-of-menoth','name' => 'Reclaimer','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '153','faction' => 'mercenaries','name' => 'Reinholdt, Gobber Speculator','type' => 'warrior','number' => '1','cost' => '1','field_allowance' => '1','parent' => ''),
	array('id' => '154','faction' => 'mercenaries','name' => 'Rhupert Carvalo, Piper of Ord','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'U','parent' => ''),
	array('id' => '155','faction' => 'cryx','name' => 'Scrap Thrall','type' => 'warrior','number' => '3','cost' => '1','field_allowance' => '3','parent' => '147'),
	array('id' => '156','faction' => 'cryx','name' => 'Skarlock Thrall','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => ''),
	array('id' => '157','faction' => 'cygnar','name' => 'Squire','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => ''),
	array('id' => '158','faction' => 'mercenaries','name' => 'Stannis Brocker','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => 'U','parent' => ''),
	array('id' => '159','faction' => 'cygnar','name' => 'Stormsmith Stormcaller','type' => 'warrior','number' => '1','cost' => '1','field_allowance' => '3','parent' => ''),
	array('id' => '160','faction' => 'protectorate-of-menoth','name' => 'The Convenant of Menoth','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'C','parent' => ''),
	array('id' => '161','faction' => 'protectorate-of-menoth','name' => 'Wrack','type' => 'warrior','number' => '3','cost' => '1','field_allowance' => '1','parent' => ''),
	array('id' => '162','faction' => 'mercenaries','name' => 'Thor Steinhammer','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'U','parent' => ''),
	array('id' => '163','faction' => 'protectorate-of-menoth','name' => 'Vassal of Menoth','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '164','faction' => 'khador','name' => 'War dog','type' => 'warrior','number' => '1','cost' => '1','field_allowance' => '1','parent' => ''),
	array('id' => '165','faction' => 'khador','name' => 'Yuri the Axe','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => 'C','parent' => ''),
	array('id' => '166','faction' => 'cygnar','name' => 'Arcane Tempest Gun Mage Officer','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '231'),
	array('id' => '167','faction' => 'cryx','name' => 'Brute Thrall','type' => 'warrior','number' => '1, 2, 3','cost' => '1, 2, 3','field_allowance' => 'U','parent' => '196'),
	array('id' => '168','faction' => 'cryx','name' => 'Cephalyx Overlords','type' => 'warrior','number' => '1','cost' => '4','field_allowance' => '1','parent' => '203'),
	array('id' => '169','faction' => 'protectorate-of-menoth','name' => 'Deliverer Sunburst Crew','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '170','faction' => 'protectorate-of-menoth','name' => 'Idrian Skirmishers Chieftain & Guide','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '1','parent' => '215'),
	array('id' => '171','faction' => 'khador','name' => 'Iron Fang Pikemen Officer & Standard','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '218'),
	array('id' => '172','faction' => 'khador','name' => 'Kayazy Assassins Underboss','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '228'),
	array('id' => '173','faction' => 'cygnar','name' => 'Long Gunner Infantry Officer & Standard','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '232'),
	array('id' => '174','faction' => 'protectorate-of-menoth','name' => 'Monolith Bearer','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '206'),
	array('id' => '175','faction' => 'mercenaries','name' => 'Mr. Walls Sea Dog Crew Quartermaster','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'U','parent' => ''),
	array('id' => '176','faction' => 'cryx','name' => 'Necrosurgeon & Stitch Thralls','type' => 'warrior','number' => '4','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '177','faction' => 'cygnar','name' => 'Precursor Knights Officer & Standard','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '241'),
	array('id' => '178','faction' => 'cryx','name' => 'Revenant Cannon Crew','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '179','faction' => 'cryx','name' => 'Satyxis Raider Sea Witch','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '197'),
	array('id' => '180','faction' => 'mercenaries','name' => 'Sea Dog Crew Rifleman','type' => 'warrior','number' => '1','cost' => '1','field_allowance' => 'U','parent' => ''),
	array('id' => '181','faction' => 'mercenaries','name' => 'Sea Dog Deck Gun','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'U','parent' => ''),
	array('id' => '182','faction' => 'cygnar','name' => 'Stormblade Infantry Officer & Standard','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '1','parent' => '234'),
	array('id' => '183','faction' => 'cygnar','name' => 'Sword Knights Officer & Standard','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '236'),
	array('id' => '184','faction' => 'protectorate-of-menoth','name' => 'Temple Flameguard Officer & Standard','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '208'),
	array('id' => '185','faction' => 'mercenaries','name' => 'The Commodore Cannon & Crew','type' => 'warrior','number' => '1','cost' => '4','field_allowance' => 'C','parent' => '22'),
	array('id' => '186','faction' => 'cygnar','name' => 'Trencher Cannon Crew','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '187','faction' => 'cygnar','name' => 'Trencher Chaingun Crew','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '188','faction' => 'cygnar','name' => 'Trencher Infantry Grenadier','type' => 'warrior','number' => '1, 2, 3','cost' => '1, 2, 3','field_allowance' => 'U','parent' => '235'),
	array('id' => '189','faction' => 'cygnar','name' => 'Trencher Infantry Officer & Sniper','type' => 'warrior','number' => '2','cost' => '3','field_allowance' => '1','parent' => '235'),
	array('id' => '190','faction' => 'khador','name' => 'Winter Guard Field Gun Crew','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '191','faction' => 'khador','name' => 'Winter Guard inf. Officer & Standard','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '221'),
	array('id' => '192','faction' => 'khador','name' => 'Winter Guard Mortar Crew','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '193','faction' => 'khador','name' => 'Winter Guard Rocketeer','type' => 'warrior','number' => '1, 2, 3','cost' => '1, 2, 3','field_allowance' => '6','parent' => '221'),
	array('id' => '194','faction' => 'cryx','name' => 'Bane Thralls','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '3','parent' => ''),
	array('id' => '195','faction' => 'cryx','name' => 'Bile Thralls','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '3','parent' => ''),
	array('id' => '196','faction' => 'cryx','name' => 'Mechanithralls','type' => 'warrior','number' => '6, 10','cost' => '3, 5','field_allowance' => '3','parent' => ''),
	array('id' => '197','faction' => 'cryx','name' => 'Satyxis Raider','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '198','faction' => 'cryx','name' => 'Revenant Crew of the Atramentous','type' => 'warrior','number' => '6, 10','cost' => '6, 9','field_allowance' => '2','parent' => ''),
	array('id' => '199','faction' => 'cryx','name' => 'Bane Knights','type' => 'warrior','number' => '6, 10','cost' => '6, 10','field_allowance' => '3','parent' => ''),
	array('id' => '200','faction' => 'cryx','name' => 'Black Ogrun Boarding Party','type' => 'warrior','number' => '3, 5','cost' => '4, 6','field_allowance' => '2','parent' => ''),
	array('id' => '201','faction' => 'cryx','name' => 'Soulhunters','type' => 'warrior','number' => '3, 5','cost' => '6, 9','field_allowance' => '1','parent' => ''),
	array('id' => '202','faction' => 'cryx','name' => 'Blackbane\'s Ghost Raiders','type' => 'warrior','number' => '6, 10','cost' => '6, 9','field_allowance' => '1','parent' => ''),
	array('id' => '203','faction' => 'cryx','name' => 'Cephalyx Slaver & Drudge Mind Slaves','type' => 'warrior','number' => '6, 10','cost' => '4, 6','field_allowance' => '2','parent' => ''),
	array('id' => '204','faction' => 'protectorate-of-menoth','name' => 'Choir of Menoth','type' => 'warrior','number' => '4, 6','cost' => '2, 3','field_allowance' => '3','parent' => ''),
	array('id' => '205','faction' => 'protectorate-of-menoth','name' => 'Deliverers','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '1','parent' => ''),
	array('id' => '206','faction' => 'protectorate-of-menoth','name' => 'Holy Zealots','type' => 'warrior','number' => '6, 10','cost' => '4, 6','field_allowance' => '3','parent' => ''),
	array('id' => '207','faction' => 'protectorate-of-menoth','name' => 'Knights Exemplar','type' => 'warrior','number' => '6','cost' => '5','field_allowance' => '3','parent' => ''),
	array('id' => '208','faction' => 'protectorate-of-menoth','name' => 'Temple Flameguard','type' => 'warrior','number' => '6, 10','cost' => '4, 6','field_allowance' => '3','parent' => ''),
	array('id' => '209','faction' => 'protectorate-of-menoth','name' => 'Flameguard Cleansers','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '210','faction' => 'protectorate-of-menoth','name' => 'Daughters of the Flame','type' => 'warrior','number' => '6','cost' => '5','field_allowance' => '2','parent' => ''),
	array('id' => '211','faction' => 'protectorate-of-menoth','name' => 'Exemplar Errants','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '3','parent' => ''),
	array('id' => '212','faction' => 'protectorate-of-menoth','name' => 'Exemplar Vengers','type' => 'warrior','number' => '3, 5','cost' => '7, 11','field_allowance' => '1','parent' => ''),
	array('id' => '213','faction' => 'protectorate-of-menoth','name' => 'Exemplar Bastions','type' => 'warrior','number' => '3, 5','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '214','faction' => 'protectorate-of-menoth','name' => 'Visgoth Juviah Rhoven & Honor guard','type' => 'warrior','number' => '3','cost' => '4','field_allowance' => 'C','parent' => ''),
	array('id' => '215','faction' => 'protectorate-of-menoth','name' => 'Idrian Skirmishers','type' => 'warrior','number' => '6, 10','cost' => '6, 10','field_allowance' => '2','parent' => ''),
	array('id' => '216','faction' => 'khador','name' => 'Battle Mechaniks','type' => 'warrior','number' => '4, 6','cost' => '2, 3','field_allowance' => '3','parent' => ''),
	array('id' => '217','faction' => 'khador','name' => 'Doom Reavers','type' => 'warrior','number' => '6','cost' => '6','field_allowance' => '2','parent' => ''),
	array('id' => '218','faction' => 'khador','name' => 'Iron Fang Pikemen','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '219','faction' => 'khador','name' => 'Man-O-War Shoktroopers','type' => 'warrior','number' => '3, 5','cost' => '6, 9','field_allowance' => '3','parent' => ''),
	array('id' => '220','faction' => 'khador','name' => 'Widowmakers','type' => 'warrior','number' => '4','cost' => '4','field_allowance' => '1','parent' => ''),
	array('id' => '221','faction' => 'khador','name' => 'Winter Guard Infantry','type' => 'warrior','number' => '6, 10','cost' => '4, 6','field_allowance' => '3','parent' => ''),
	array('id' => '222','faction' => 'khador','name' => 'Greylord Ternion','type' => 'warrior','number' => '3','cost' => '4','field_allowance' => '3','parent' => ''),
	array('id' => '223','faction' => 'khador','name' => 'Kossite Woodsmen','type' => 'warrior','number' => '6, 10','cost' => '4, 6','field_allowance' => '2','parent' => ''),
	array('id' => '224','faction' => 'khador','name' => 'Assault Kommandos','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '225','faction' => 'khador','name' => 'Iron Fang Uhlans','type' => 'warrior','number' => '3, 5','cost' => '7, 11','field_allowance' => '1','parent' => ''),
	array('id' => '226','faction' => 'khador','name' => 'Man-O-War Demolition Corps','type' => 'warrior','number' => '3, 5','cost' => '6, 9','field_allowance' => '2','parent' => ''),
	array('id' => '227','faction' => 'khador','name' => 'Great Bears of Gallowswood','type' => 'warrior','number' => '3','cost' => '5','field_allowance' => 'C','parent' => ''),
	array('id' => '228','faction' => 'khador','name' => 'Kayazy Assassins','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '229','faction' => 'cryx','name' => 'Bloodgorgers','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '230','faction' => 'cryx','name' => 'The Withershadow Combine','type' => 'warrior','number' => '3','cost' => '5','field_allowance' => 'C','parent' => ''),
	array('id' => '231','faction' => 'cygnar','name' => 'Arcane Tempest Gun Mages','type' => 'warrior','number' => '6','cost' => '6','field_allowance' => '2','parent' => ''),
	array('id' => '232','faction' => 'cygnar','name' => 'Long Gunner Infantry','type' => 'warrior','number' => '6, 10','cost' => '6, 10','field_allowance' => '2','parent' => ''),
	array('id' => '233','faction' => 'cygnar','name' => 'Field Mechaniks','type' => 'warrior','number' => '4, 6','cost' => '2, 3','field_allowance' => '3','parent' => ''),
	array('id' => '234','faction' => 'cygnar','name' => 'Stormblade Infantry','type' => 'warrior','number' => '6','cost' => '5','field_allowance' => '2','parent' => ''),
	array('id' => '235','faction' => 'cygnar','name' => 'Trencher Infantry','type' => 'warrior','number' => '6, 10','cost' => '6, 10','field_allowance' => '2','parent' => ''),
	array('id' => '236','faction' => 'cygnar','name' => 'Sword Knights','type' => 'warrior','number' => '6, 10','cost' => '4, 6','field_allowance' => '2','parent' => ''),
	array('id' => '237','faction' => 'cygnar','name' => 'Ranger','type' => 'warrior','number' => '6','cost' => '5','field_allowance' => '2','parent' => ''),
	array('id' => '238','faction' => 'cygnar','name' => 'Stormguard','type' => 'warrior','number' => '6, 9','cost' => '6, 10','field_allowance' => '2','parent' => ''),
	array('id' => '239','faction' => 'cygnar','name' => 'Storm Lances','type' => 'warrior','number' => '3, 5','cost' => '7, 11','field_allowance' => '1','parent' => ''),
	array('id' => '240','faction' => 'cygnar','name' => 'Black 13th Strike Team','type' => 'warrior','number' => '3','cost' => '4','field_allowance' => 'C','parent' => ''),
	array('id' => '241','faction' => 'cygnar','name' => 'Precursor Knights','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '242','faction' => 'mercenaries','name' => 'Greygore Boomhowler & Co.','type' => 'warrior','number' => '6, 10','cost' => '6, 9','field_allowance' => 'U','parent' => ''),
	array('id' => '243','faction' => 'mercenaries','name' => 'Herne & Jonne','type' => 'warrior','number' => '2','cost' => '3','field_allowance' => 'U','parent' => ''),
	array('id' => '244','faction' => 'mercenaries','name' => 'Captain Sam Machorne & the Devil Dogs','type' => 'warrior','number' => '6, 10','cost' => '5, 7','field_allowance' => 'U','parent' => ''),
	array('id' => '245','faction' => 'mercenaries','name' => 'Croe\'s Cutthroats','type' => 'warrior','number' => '6, 10','cost' => '7, 10','field_allowance' => 'U','parent' => ''),
	array('id' => '246','faction' => 'mercenaries','name' => 'Cylena Raefyll & Nyss Hunters','type' => 'warrior','number' => '6, 10','cost' => '6, 10','field_allowance' => 'U','parent' => ''),
	array('id' => '247','faction' => 'mercenaries','name' => 'Hammerfall High Shield Gun Corps','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => 'U','parent' => ''),
	array('id' => '248','faction' => 'mercenaries','name' => 'Horgenhold Forge Guard','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => 'U','parent' => ''),
	array('id' => '249','faction' => 'mercenaries','name' => 'Steelhead Halberdiers','type' => 'warrior','number' => '6, 10','cost' => '4, 6','field_allowance' => 'U','parent' => ''),
	array('id' => '250','faction' => 'mercenaries','name' => 'Alexia Ciannor & the Risen','type' => 'warrior','number' => '7','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '251','faction' => 'mercenaries','name' => 'Lord Aiyanna & Master Holt','type' => 'warrior','number' => '2','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '252','faction' => 'mercenaries','name' => 'Press Gangers','type' => 'warrior','number' => '6, 10','cost' => '4, 6','field_allowance' => 'U','parent' => ''),
	array('id' => '253','faction' => 'mercenaries','name' => 'Sea Dog Crew','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => 'U','parent' => ''),
	array('id' => '254','faction' => 'mercenaries','name' => 'Steelhead Heavy Cavalery','type' => 'warrior','number' => '3, 5','cost' => '6, 10','field_allowance' => 'U','parent' => ''),
	array('id' => '258','faction' => 'protectorate-of-menoth','name' => 'Templar','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'U','parent' => ''),
	array('id' => '271','faction' => 'cryx','name' => 'Satixis Blood Witches','type' => 'warrior','number' => '6, 10','cost' => '4, 6','field_allowance' => '2','parent' => ''),
	array('id' => '259','faction' => 'cygnar','name' => 'Cyclone','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '260','faction' => 'khador','name' => 'Decimator','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '261','faction' => 'cryx','name' => 'Corruptor','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'U','parent' => ''),
	array('id' => '262','faction' => 'protectorate-of-menoth','name' => 'Vice Scrutator Vindictus','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '263','faction' => 'protectorate-of-menoth','name' => 'Vigilant','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '264','faction' => 'protectorate-of-menoth','name' => 'Exemplar Cinerators','type' => 'warrior','number' => '3, 5','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '265','faction' => 'protectorate-of-menoth','name' => 'Exemplar Errant Officer and Standard','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '211'),
	array('id' => '266','faction' => 'protectorate-of-menoth','name' => 'Exemplar Errant Seneschal','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '267','faction' => 'protectorate-of-menoth','name' => 'Vassal Mechanik','type' => 'warrior','number' => '1','cost' => '1','field_allowance' => '3','parent' => ''),
	array('id' => '268','faction' => 'cryx','name' => 'Lich Lord Venethrax','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '269','faction' => 'cryx','name' => 'Ripjaw','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '270','faction' => 'cryx','name' => 'Bane Thrall Officer & Standard','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '1','parent' => '194'),
	array('id' => '272','faction' => 'cryx','name' => 'Satixis Blood Hag','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '271'),
	array('id' => '273','faction' => 'cryx','name' => 'Satixis Raider Captain','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '274','faction' => 'cryx','name' => 'Warwitch Siren','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '275','faction' => 'cygnar','name' => 'Captain Kara Sloan','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '276','faction' => 'cygnar','name' => 'Firefly','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '277','faction' => 'cygnar','name' => 'Stormblade Infantry Storm Gunner','type' => 'warrior','number' => '1, 2, 3','cost' => '1, 2, 3','field_allowance' => '2','parent' => '234'),
	array('id' => '278','faction' => 'cygnar','name' => 'Trencher Commandos','type' => 'warrior','number' => '6, 10','cost' => '6, 10','field_allowance' => '2','parent' => ''),
	array('id' => '279','faction' => 'cygnar','name' => 'Trencher Commandos Scattergunners','type' => 'warrior','number' => '1, 2, 3','cost' => '1, 2, 3','field_allowance' => '2','parent' => '278'),
	array('id' => '280','faction' => 'cygnar','name' => 'Stormsmith Storm Tower','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '281','faction' => 'cygnar','name' => 'Trench Master Gunner','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '282','faction' => 'khador','name' => 'Kommander Strakhov','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '283','faction' => 'khador','name' => 'Assault Kommando Flame Thrower','type' => 'warrior','number' => '1, 2, 3','cost' => '1, 2, 3','field_allowance' => '2','parent' => '224'),
	array('id' => '284','faction' => 'khador','name' => 'Greylord Escort','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '217'),
	array('id' => '285','faction' => 'khador','name' => 'Man-O-War Bombardiers','type' => 'warrior','number' => '3, 5','cost' => '7, 11','field_allowance' => '1','parent' => ''),
	array('id' => '286','faction' => 'khador','name' => 'Winter Guard Rifle Corps','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '3','parent' => ''),
	array('id' => '287','faction' => 'khador','name' => 'Widowmaker Marksman','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => ''),
	array('id' => '288','faction' => 'khador','name' => 'Uhlan Kovnik Markov','type' => 'warrior','number' => '1','cost' => '4','field_allowance' => 'C','parent' => ''),
	array('id' => '289','faction' => 'retribution-of-scyrah','name' => 'Garryth, Blade of Retribution','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '290','faction' => 'retribution-of-scyrah','name' => 'Kaelyssa, Night\\\'s Whisper','type' => 'casterlock','number' => '1','cost' => '-7','field_allowance' => 'C','parent' => ''),
	array('id' => '291','faction' => 'retribution-of-scyrah','name' => 'Adeptis Rahn','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '292','faction' => 'retribution-of-scyrah','name' => 'Ravyn, Eternal Light','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '293','faction' => 'retribution-of-scyrah','name' => 'Dawnlord Vyros','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '294','faction' => 'retribution-of-scyrah','name' => 'Chimera','type' => 'jackbeast','number' => '1','cost' => '6','field_allowance' => 'U','parent' => ''),
	array('id' => '295','faction' => 'retribution-of-scyrah','name' => 'Gorgon','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '296','faction' => 'retribution-of-scyrah','name' => 'Griffon','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '297','faction' => 'retribution-of-scyrah','name' => 'Hydra','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '298','faction' => 'retribution-of-scyrah','name' => 'Manticore','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'U','parent' => ''),
	array('id' => '299','faction' => 'retribution-of-scyrah','name' => 'Phoenix','type' => 'jackbeast','number' => '1','cost' => '10','field_allowance' => 'U','parent' => ''),
	array('id' => '300','faction' => 'retribution-of-scyrah','name' => 'Dawnguard Invictors','type' => 'warrior','number' => '6, 10','cost' => '6, 10','field_allowance' => '2','parent' => ''),
	array('id' => '301','faction' => 'retribution-of-scyrah','name' => 'Dawnguard Invictors Officer & Standard','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '300'),
	array('id' => '302','faction' => 'retribution-of-scyrah','name' => 'Dawnguard Sentinels','type' => 'warrior','number' => '6, 10','cost' => '6, 9','field_allowance' => '2','parent' => ''),
	array('id' => '303','faction' => 'retribution-of-scyrah','name' => 'Dawnguard Sentinel Offcer & Standard','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '302'),
	array('id' => '304','faction' => 'retribution-of-scyrah','name' => 'Dawnguard Destors','type' => 'warrior','number' => '3, 5','cost' => '7, 11','field_allowance' => '1','parent' => ''),
	array('id' => '305','faction' => 'retribution-of-scyrah','name' => 'House Shyeel Battle Mages','type' => 'warrior','number' => '6','cost' => '5','field_allowance' => '2','parent' => ''),
	array('id' => '306','faction' => 'retribution-of-scyrah','name' => 'Houseguard Haleberdiers','type' => 'warrior','number' => '6, 10','cost' => '4, 7','field_allowance' => '3','parent' => ''),
	array('id' => '307','faction' => 'retribution-of-scyrah','name' => 'Houseguard Haleberdiers Officer & Standard','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '306'),
	array('id' => '308','faction' => 'retribution-of-scyrah','name' => 'Houseguard Riflemen','type' => 'warrior','number' => '6, 10','cost' => '3, 8','field_allowance' => '3','parent' => ''),
	array('id' => '309','faction' => 'retribution-of-scyrah','name' => 'Houseguard Riflemen Officer & Standard','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '308'),
	array('id' => '310','faction' => 'retribution-of-scyrah','name' => 'Mage Hunter Strike Force','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '311','faction' => 'retribution-of-scyrah','name' => 'Mage Hunter Strike Force Commander','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '310'),
	array('id' => '312','faction' => 'retribution-of-scyrah','name' => 'Stormfall Archers','type' => 'warrior','number' => '4','cost' => '5','field_allowance' => '2','parent' => ''),
	array('id' => '313','faction' => 'retribution-of-scyrah','name' => 'Souless Escort','type' => 'warrior','number' => '1, 2, 3','cost' => '1, 2, 3','field_allowance' => '3','parent' => ''),
	array('id' => '314','faction' => 'retribution-of-scyrah','name' => 'Arcanist','type' => 'warrior','number' => '1','cost' => '1','field_allowance' => '2','parent' => ''),
	array('id' => '315','faction' => 'retribution-of-scyrah','name' => 'Dawnguard Destor Thane','type' => 'warrior','number' => '1','cost' => '4','field_allowance' => '2','parent' => ''),
	array('id' => '316','faction' => 'retribution-of-scyrah','name' => 'Dawnguard Scyir','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '317','faction' => 'retribution-of-scyrah','name' => 'House Shyeel Magister','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '318','faction' => 'retribution-of-scyrah','name' => 'Mage Hunter Assassin','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '319','faction' => 'retribution-of-scyrah','name' => 'Ghost Sniper','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '321','faction' => 'retribution-of-scyrah','name' => 'Fane Knight Skeryth Issyen','type' => 'warrior','number' => '1','cost' => '5','field_allowance' => 'C','parent' => ''),
	array('id' => '322','faction' => 'retribution-of-scyrah','name' => 'Nayl','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'C','parent' => ''),
	array('id' => '323','faction' => 'retribution-of-scyrah','name' => 'Narn, Mage hunter of Ios','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => 'C','parent' => ''),
	array('id' => '324','faction' => 'trollbloods','name' => 'Grim Angus','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '325','faction' => 'trollbloods','name' => 'Grissel Bloodsong, Fell Caller','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '326','faction' => 'trollbloods','name' => 'Hoarluk Doomshaper, Shaman','type' => 'casterlock','number' => '1','cost' => '-7','field_allowance' => 'C','parent' => ''),
	array('id' => '327','faction' => 'trollbloods','name' => 'Hoarluk Doomshaper, Rage of Dhunia','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '328','faction' => 'trollbloods','name' => 'Captain Gunnbjorn','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '329','faction' => 'trollbloods','name' => 'Madrak Ironhide, Thornwood Chieftain','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '330','faction' => 'trollbloods','name' => 'Madrak ironhide, World Ender','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '331','faction' => 'trollbloods','name' => 'Borka Kegslayer & Keg Carrier','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '332','faction' => 'trollbloods','name' => 'Calandra Truthsayer, Oracle','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '333','faction' => 'trollbloods','name' => 'Pyre Troll','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '334','faction' => 'trollbloods','name' => 'Slag Troll','type' => 'jackbeast','number' => '1','cost' => '6','field_allowance' => 'U','parent' => ''),
	array('id' => '335','faction' => 'trollbloods','name' => 'Swamp Troll','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '336','faction' => 'trollbloods','name' => 'Troll Axer','type' => 'jackbeast','number' => '1','cost' => '6','field_allowance' => 'U','parent' => ''),
	array('id' => '337','faction' => 'trollbloods','name' => 'Troll Bouncer','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '338','faction' => 'trollbloods','name' => 'Troll Impaler','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '339','faction' => 'trollbloods','name' => 'Winter Troll','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '340','faction' => 'trollbloods','name' => 'Dire Troll Blitzer','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '341','faction' => 'trollbloods','name' => 'Dire Troll Bomber','type' => 'jackbeast','number' => '1','cost' => '10','field_allowance' => 'U','parent' => ''),
	array('id' => '342','faction' => 'trollbloods','name' => 'Dire Troll Mauler','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '343','faction' => 'trollbloods','name' => 'Earthborn Dire Troll','type' => 'jackbeast','number' => '1','cost' => '10','field_allowance' => 'U','parent' => ''),
	array('id' => '344','faction' => 'trollbloods','name' => 'Mulg the Ancient','type' => 'jackbeast','number' => '1','cost' => '12','field_allowance' => 'C','parent' => ''),
	array('id' => '345','faction' => 'trollbloods','name' => 'Kriel Warriors','type' => 'warrior','number' => '6, 10','cost' => '4, 6','field_allowance' => '3','parent' => ''),
	array('id' => '346','faction' => 'trollbloods','name' => 'Kriel Warrior Standard & Piper','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '345'),
	array('id' => '347','faction' => 'trollbloods','name' => 'Kriel Warrior Caber Thrower','type' => 'warrior','number' => '1, 2, 3','cost' => '1, 2, 3','field_allowance' => '3','parent' => '345'),
	array('id' => '348','faction' => 'trollbloods','name' => 'Pyg Burrowers','type' => 'warrior','number' => '6, 10','cost' => '4, 6','field_allowance' => '1','parent' => ''),
	array('id' => '349','faction' => 'trollbloods','name' => 'Krielstone Bearer & Stone Scribes','type' => 'warrior','number' => '4, 6','cost' => '3, 4','field_allowance' => '1','parent' => ''),
	array('id' => '350','faction' => 'trollbloods','name' => 'Stone Scribe Elder','type' => 'warrior','number' => '1','cost' => '1','field_allowance' => '1','parent' => '349'),
	array('id' => '351','faction' => 'trollbloods','name' => 'Pyg Bushwhackers','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '352','faction' => 'trollbloods','name' => 'Thumper Crew','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '353','faction' => 'trollbloods','name' => 'Trollkin Champions','type' => 'warrior','number' => '3, 5','cost' => '6, 10','field_allowance' => '2','parent' => ''),
	array('id' => '354','faction' => 'trollbloods','name' => 'Skaldi Bonehammer','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => 'C','parent' => '353'),
	array('id' => '355','faction' => 'trollbloods','name' => 'Trollkin Fennblades','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '356','faction' => 'trollbloods','name' => 'Trollkin Fennblade Officer & Drummer','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '355'),
	array('id' => '357','faction' => 'trollbloods','name' => 'Trollkin Long Riders','type' => 'warrior','number' => '3, 5','cost' => '7, 11','field_allowance' => '1','parent' => ''),
	array('id' => '358','faction' => 'trollbloods','name' => 'Trollkin Runeshapers','type' => 'warrior','number' => '3','cost' => '4','field_allowance' => '2','parent' => ''),
	array('id' => '359','faction' => 'trollbloods','name' => 'Scatter Gunners','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '360','faction' => 'trollbloods','name' => 'Trollkin Scouts','type' => 'warrior','number' => '6','cost' => '5','field_allowance' => '2','parent' => ''),
	array('id' => '361','faction' => 'trollbloods','name' => 'Trollkin Sluggers','type' => 'warrior','number' => '3, 5','cost' => '5, 8','field_allowance' => '1','parent' => ''),
	array('id' => '362','faction' => 'trollbloods','name' => 'Fell Caller Hero','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '363','faction' => 'trollbloods','name' => 'Stone Scribe Chronicler','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => ''),
	array('id' => '364','faction' => 'trollbloods','name' => 'Troll Whelps','type' => 'warrior','number' => '5','cost' => '2','field_allowance' => '3','parent' => ''),
	array('id' => '365','faction' => 'trollbloods','name' => 'Trollkin Champion Hero','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '366','faction' => 'trollbloods','name' => 'Trollkin Runebearer','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => ''),
	array('id' => '367','faction' => 'trollbloods','name' => 'Trollkin Skinner','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '368','faction' => 'trollbloods','name' => 'Horthol, Long Rider Hero','type' => 'warrior','number' => '1','cost' => '5','field_allowance' => 'C','parent' => ''),
	array('id' => '369','faction' => 'trollbloods','name' => 'Janissa Stonetide','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => 'C','parent' => ''),
	array('id' => '370','faction' => 'circle-orboros','name' => 'Baldur The Stonegleaver','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '371','faction' => 'circle-orboros','name' => 'Cassius The Oathkeeper & Wurmwood','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '372','faction' => 'circle-orboros','name' => 'Kaya The Wildborne','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '373','faction' => 'circle-orboros','name' => 'Kaya the Moonhunter & Laris','type' => 'casterlock','number' => '1','cost' => '-3','field_allowance' => 'C','parent' => ''),
	array('id' => '374','faction' => 'circle-orboros','name' => 'Kromag The Ravenous','type' => 'casterlock','number' => '1','cost' => '-4','field_allowance' => 'C','parent' => ''),
	array('id' => '375','faction' => 'circle-orboros','name' => 'Krueger The Stormwrath','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '376','faction' => 'circle-orboros','name' => 'Krueger the Stormwlord','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '377','faction' => 'circle-orboros','name' => 'Mohsar The Desertwalker','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '378','faction' => 'circle-orboros','name' => 'Morvahna The Autumnblade','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '379','faction' => 'circle-orboros','name' => 'Argus','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '380','faction' => 'circle-orboros','name' => 'Gorax','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '381','faction' => 'circle-orboros','name' => 'Woldwatcher','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '382','faction' => 'circle-orboros','name' => 'Woldwyrd','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '383','faction' => 'circle-orboros','name' => 'Shadowhorn Satyr','type' => 'jackbeast','number' => '1','cost' => '7','field_allowance' => 'U','parent' => ''),
	array('id' => '384','faction' => 'circle-orboros','name' => 'Gnarlhorn Satyr','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'U','parent' => ''),
	array('id' => '385','faction' => 'circle-orboros','name' => 'Feral Warlpwolf','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '386','faction' => 'circle-orboros','name' => 'Pureblood Warpwolf','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '387','faction' => 'circle-orboros','name' => 'Warpwolf Stalker','type' => 'jackbeast','number' => '1','cost' => '10','field_allowance' => 'U','parent' => ''),
	array('id' => '388','faction' => 'circle-orboros','name' => 'Woldwarden','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '389','faction' => 'circle-orboros','name' => 'Wold Guardian','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '390','faction' => 'circle-orboros','name' => 'Megalith','type' => 'jackbeast','number' => '1','cost' => '11','field_allowance' => 'C','parent' => ''),
	array('id' => '391','faction' => 'circle-orboros','name' => 'Druids of Orboros','type' => 'warrior','number' => '6','cost' => '7','field_allowance' => '2','parent' => ''),
	array('id' => '392','faction' => 'circle-orboros','name' => 'Druids of Orboros Overseer','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '391'),
	array('id' => '393','faction' => 'circle-orboros','name' => 'Druid Stoneward & Woldstalkers','type' => 'warrior','number' => '6','cost' => '5','field_allowance' => '2','parent' => ''),
	array('id' => '394','faction' => 'circle-orboros','name' => 'Sentry Stone & Mannikins','type' => 'warrior','number' => '4','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '395','faction' => 'circle-orboros','name' => 'Shifting Stones','type' => 'warrior','number' => '3','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '396','faction' => 'circle-orboros','name' => 'Stone Keeper','type' => 'warrior','number' => '1','cost' => '1','field_allowance' => '1','parent' => '395'),
	array('id' => '397','faction' => 'circle-orboros','name' => 'Reeves of Orboros','type' => 'warrior','number' => '6, 10','cost' => '6, 10','field_allowance' => '2','parent' => ''),
	array('id' => '398','faction' => 'circle-orboros','name' => 'Reves of Orboros Chieftain & Standard','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '397'),
	array('id' => '399','faction' => 'circle-orboros','name' => 'Tharn Bloodtrackers','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '1','parent' => ''),
	array('id' => '400','faction' => 'circle-orboros','name' => 'Nuala The Huntress','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'C','parent' => '399'),
	array('id' => '401','faction' => 'circle-orboros','name' => 'Tharn Bloodweavers','type' => 'warrior','number' => '6','cost' => '5','field_allowance' => '2','parent' => ''),
	array('id' => '402','faction' => 'circle-orboros','name' => 'Tharn Wolf Riders','type' => 'warrior','number' => '3, 5','cost' => '6, 10','field_allowance' => '1','parent' => ''),
	array('id' => '403','faction' => 'circle-orboros','name' => 'Tharn Ravagers','type' => 'warrior','number' => '4,6','cost' => '6,9','field_allowance' => '2','parent' => ''),
	array('id' => '404','faction' => 'circle-orboros','name' => 'Tharn Ravager Chieftain','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '403'),
	array('id' => '405','faction' => 'circle-orboros','name' => 'Tharn Ravager Shaman','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '403'),
	array('id' => '406','faction' => 'circle-orboros','name' => 'Warpborn Skinwalkers','type' => 'warrior','number' => '3, 5','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '407','faction' => 'circle-orboros','name' => 'Wolves of Orboros','type' => 'warrior','number' => '6, 10','cost' => '4, 6','field_allowance' => '3','parent' => ''),
	array('id' => '408','faction' => 'circle-orboros','name' => 'Wolves of Orboros Chieftain & Standard','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '407'),
	array('id' => '409','faction' => 'circle-orboros','name' => 'Blackglad Wayfarer','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '410','faction' => 'circle-orboros','name' => 'Druid Wilder','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => ''),
	array('id' => '411','faction' => 'circle-orboros','name' => 'Reeve Hunter','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '412','faction' => 'circle-orboros','name' => 'Tharn Ravager White Mane','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '413','faction' => 'circle-orboros','name' => 'War Wolf','type' => 'warrior','number' => '1','cost' => '1','field_allowance' => '3','parent' => ''),
	array('id' => '414','faction' => 'circle-orboros','name' => 'Lord of the Feast','type' => 'warrior','number' => '1','cost' => '4','field_allowance' => 'C','parent' => ''),
	array('id' => '415','faction' => 'circle-orboros','name' => 'Wolf Lord Morraig','type' => 'warrior','number' => '1','cost' => '5','field_allowance' => 'C','parent' => ''),
	array('id' => '416','faction' => 'protectorate-of-menoth','name' => 'Flame Bringers','type' => 'warrior','number' => '3, 5','cost' => '6, 10','field_allowance' => '2','parent' => ''),
	array('id' => '417','faction' => 'cryx','name' => 'Malice','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'C','parent' => ''),
	array('id' => '418','faction' => 'cryx','name' => 'Erebus','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'C','parent' => ''),
	array('id' => '419','faction' => 'cryx','name' => 'Kraken','type' => 'jackbeast','number' => '1','cost' => '19','field_allowance' => '2','parent' => ''),
	array('id' => '420','faction' => 'cryx','name' => 'Scavenger','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '421','faction' => 'cryx','name' => 'Asphyxious the Hellbringer & Vociferon','type' => 'casterlock','number' => '1','cost' => '-4','field_allowance' => 'C','parent' => ''),
	array('id' => '422','faction' => 'cryx','name' => 'Desecrator','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '423','faction' => 'legion-of-everblight','name' => 'Thagrosh, Prophet of  Everblight','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '424','faction' => 'legion-of-everblight','name' => 'Lylyth, Herald of Everblight','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '425','faction' => 'legion-of-everblight','name' => 'Absylonia, Terror of Everblight','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '426','faction' => 'legion-of-everblight','name' => 'Bethayne, Voice of Everblight & Belphagor','type' => 'casterlock','number' => '2','cost' => '-3','field_allowance' => 'C','parent' => ''),
	array('id' => '427','faction' => 'legion-of-everblight','name' => 'Lylyth, Shadow of Everblight','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '428','faction' => 'legion-of-everblight','name' => 'Rhyas, Sigil of Everblight','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '429','faction' => 'legion-of-everblight','name' => 'Saeryn, Omen of Everblight','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '430','faction' => 'legion-of-everblight','name' => 'Thagrosh, The messiah','type' => 'casterlock','number' => '1','cost' => '-3','field_allowance' => 'C','parent' => ''),
	array('id' => '431','faction' => 'legion-of-everblight','name' => 'Vayl, Disciple of Everblight','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '432','faction' => 'legion-of-everblight','name' => 'Harrier','type' => 'jackbeast','number' => '1','cost' => '2','field_allowance' => 'U','parent' => ''),
	array('id' => '433','faction' => 'legion-of-everblight','name' => 'Shredder','type' => 'jackbeast','number' => '1','cost' => '2','field_allowance' => 'U','parent' => ''),
	array('id' => '434','faction' => 'legion-of-everblight','name' => 'Stinger','type' => 'jackbeast','number' => '1','cost' => '2','field_allowance' => 'U','parent' => ''),
	array('id' => '435','faction' => 'legion-of-everblight','name' => 'Nephilim bolt thrower','type' => 'jackbeast','number' => '1','cost' => '6','field_allowance' => 'U','parent' => ''),
	array('id' => '436','faction' => 'legion-of-everblight','name' => 'Nephilim protector','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '437','faction' => 'legion-of-everblight','name' => 'Nephilim soldier','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '438','faction' => 'legion-of-everblight','name' => 'Raek','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '439','faction' => 'legion-of-everblight','name' => 'Teraph','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '440','faction' => 'legion-of-everblight','name' => 'Angelius','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '441','faction' => 'legion-of-everblight','name' => 'Carnivean','type' => 'jackbeast','number' => '1','cost' => '11','field_allowance' => 'U','parent' => ''),
	array('id' => '442','faction' => 'legion-of-everblight','name' => 'Ravagore','type' => 'jackbeast','number' => '1','cost' => '10','field_allowance' => 'U','parent' => ''),
	array('id' => '443','faction' => 'legion-of-everblight','name' => 'Scythean','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '444','faction' => 'legion-of-everblight','name' => 'Seraph','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'U','parent' => ''),
	array('id' => '445','faction' => 'legion-of-everblight','name' => 'Typhon','type' => 'jackbeast','number' => '1','cost' => '12','field_allowance' => 'C','parent' => ''),
	array('id' => '446','faction' => 'legion-of-everblight','name' => 'Blighted Nyss Archers','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '447','faction' => 'legion-of-everblight','name' => 'Blighted Nyss Archer Officer & Ammo porter','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '446'),
	array('id' => '448','faction' => 'legion-of-everblight','name' => 'Blighted Nyss Grotesques','type' => 'warrior','number' => '6, 10','cost' => '4,6','field_allowance' => '2','parent' => ''),
	array('id' => '449','faction' => 'legion-of-everblight','name' => 'Blighted Nyss Legionnaires','type' => 'warrior','number' => '6, 10','cost' => '4, 6','field_allowance' => '2','parent' => ''),
	array('id' => '450','faction' => 'legion-of-everblight','name' => 'Blighted Nyss Hex Hunters','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '3','parent' => ''),
	array('id' => '451','faction' => 'legion-of-everblight','name' => 'Bayal, Hound of Everblight','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => 'C','parent' => '450'),
	array('id' => '452','faction' => 'legion-of-everblight','name' => 'Blighted Nyss Raptors','type' => 'warrior','number' => '3, 5','cost' => '6, 10','field_allowance' => '1','parent' => ''),
	array('id' => '453','faction' => 'legion-of-everblight','name' => 'Blighted Nyss Scather Crew','type' => 'warrior','number' => '3','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '454','faction' => 'legion-of-everblight','name' => 'Blighted Nyss Striders','type' => 'warrior','number' => '6','cost' => '6','field_allowance' => '2','parent' => ''),
	array('id' => '455','faction' => 'legion-of-everblight','name' => 'Blighted Nyss Officer & Musician','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '1','parent' => '454'),
	array('id' => '456','faction' => 'legion-of-everblight','name' => 'Blighted Nyss Swordsman','type' => 'warrior','number' => '6, 10','cost' => '5, 8','field_allowance' => '2','parent' => ''),
	array('id' => '457','faction' => 'legion-of-everblight','name' => 'Blighted Nyss Swordsman Abbot & Champion','type' => 'warrior','number' => '2','cost' => '3','field_allowance' => '1','parent' => '456'),
	array('id' => '458','faction' => 'legion-of-everblight','name' => 'Blighted Ogrun Warmongers','type' => 'warrior','number' => '3, 5','cost' => '5, 8','field_allowance' => '3','parent' => ''),
	array('id' => '459','faction' => 'legion-of-everblight','name' => 'Blighted Ogrun Warspears','type' => 'warrior','number' => '3, 5','cost' => '5, 8','field_allowance' => '3','parent' => ''),
	array('id' => '460','faction' => 'legion-of-everblight','name' => 'Blackfrost Shard','type' => 'warrior','number' => '3','cost' => '5','field_allowance' => 'C','parent' => ''),
	array('id' => '461','faction' => 'legion-of-everblight','name' => 'Spawning Vessel','type' => 'warrior','number' => '4, 6','cost' => '2,3','field_allowance' => '1','parent' => ''),
	array('id' => '462','faction' => 'legion-of-everblight','name' => 'Blighted Nyss Sheperd','type' => 'warrior','number' => '1','cost' => '1','field_allowance' => '2','parent' => ''),
	array('id' => '463','faction' => 'legion-of-everblight','name' => 'Blighted Nyss Sorceress & Hellion','type' => 'warrior','number' => '2','cost' => '4','field_allowance' => '2','parent' => ''),
	array('id' => '464','faction' => 'legion-of-everblight','name' => 'The Forsaken','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '465','faction' => 'legion-of-everblight','name' => 'Incubus','type' => 'warrior','number' => '5','cost' => '5','field_allowance' => '2','parent' => ''),
	array('id' => '466','faction' => 'legion-of-everblight','name' => 'Strider Deathstalker','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '467','faction' => 'legion-of-everblight','name' => 'Spell Martyr','type' => 'warrior','number' => '1, 2, 3','cost' => '1, 2, 3','field_allowance' => '1','parent' => ''),
	array('id' => '468','faction' => 'legion-of-everblight','name' => 'Warmonger War Chief','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '469','faction' => 'legion-of-everblight','name' => 'Annyssa Ryvaal, Talon of Everblight','type' => 'warrior','number' => '3 ','cost' => '4 ','field_allowance' => 'C','parent' => ''),
	array('id' => '470','faction' => 'cygnar','name' => 'Constance Blaize, Knight of the Prophet','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '471','faction' => 'cygnar','name' => 'Minuteman','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '472','faction' => 'cygnar','name' => 'Avenger','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '473','faction' => 'cygnar','name' => 'Gallant','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'C','parent' => ''),
	array('id' => '474','faction' => 'cygnar','name' => 'Triumph','type' => 'jackbeast','number' => '1','cost' => '11','field_allowance' => 'C','parent' => ''),
	array('id' => '475','faction' => 'cygnar','name' => 'Captain Jonas Murdoch','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'C','parent' => ''),
	array('id' => '476','faction' => 'cygnar','name' => 'Archduke Alain Runewood, Lord of Fahrin','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => 'C','parent' => ''),
	array('id' => '477','faction' => 'cygnar','name' => 'Storm Strider','type' => 'warrior','number' => '1','cost' => '9','field_allowance' => '2','parent' => ''),
	array('id' => '478','faction' => 'protectorate-of-menoth','name' => 'Thyra, Flame of Sorrow','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '479','faction' => 'protectorate-of-menoth','name' => 'Sanctifier','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '480','faction' => 'protectorate-of-menoth','name' => 'Scourge of Heresy','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'C','parent' => ''),
	array('id' => '481','faction' => 'protectorate-of-menoth','name' => 'Blood of Martyrs','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'C','parent' => ''),
	array('id' => '482','faction' => 'protectorate-of-menoth','name' => 'Attendant Priest','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '483','faction' => 'protectorate-of-menoth','name' => 'Flameguard Cleanser Officer','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '209'),
	array('id' => '484','faction' => 'protectorate-of-menoth','name' => 'Nicia, Tear of Vengeance','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => 'C','parent' => ''),
	array('id' => '485','faction' => 'protectorate-of-menoth','name' => 'Vessel of Judgement','type' => 'warrior','number' => '1','cost' => '9','field_allowance' => '2','parent' => ''),
	array('id' => '486','faction' => 'khador','name' => 'Kommander Hakevich, the Iron Wolf','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '487','faction' => 'khador','name' => 'Demolisher','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '488','faction' => 'khador','name' => 'Black Ivan','type' => 'jackbeast','number' => '1','cost' => '10','field_allowance' => 'C','parent' => ''),
	array('id' => '489','faction' => 'khador','name' => 'Torch','type' => 'jackbeast','number' => '1','cost' => '10','field_allowance' => 'C','parent' => ''),
	array('id' => '490','faction' => 'khador','name' => 'Battle Mechanik Officer','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => '216'),
	array('id' => '491','faction' => 'khador','name' => 'Kayazy Eliminators','type' => 'warrior','number' => '2','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '492','faction' => 'khador','name' => 'Koldun Kapitan Valachev','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'C','parent' => ''),
	array('id' => '493','faction' => 'khador','name' => 'Gun Carriage','type' => 'warrior','number' => '1','cost' => '9','field_allowance' => '2','parent' => ''),
	array('id' => '494','faction' => 'circle-orboros','name' => 'Winter Argus','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '495','faction' => 'cryx','name' => 'Lord Exhumator Scaverous','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '496','faction' => 'cryx','name' => 'Revenant Crew Rifleman','type' => 'warrior','number' => '1, 2, 3','cost' => '1, 2, 3','field_allowance' => '2','parent' => '198'),
	array('id' => '497','faction' => 'cryx','name' => 'Iron Lich Overseer','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '498','faction' => 'cryx','name' => 'Wraith Engine','type' => 'warrior','number' => '1','cost' => '9','field_allowance' => '2','parent' => ''),
	array('id' => '499','faction' => 'retribution-of-scyrah','name' => 'Lord Arcanist Ossyan','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '500','faction' => 'retribution-of-scyrah','name' => 'Aspis','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '501','faction' => 'retribution-of-scyrah','name' => 'Banshee','type' => 'jackbeast','number' => '1','cost' => '10','field_allowance' => 'U','parent' => ''),
	array('id' => '502','faction' => 'retribution-of-scyrah','name' => 'Daemon','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'U','parent' => ''),
	array('id' => '503','faction' => 'retribution-of-scyrah','name' => 'Sphinx','type' => 'jackbeast','number' => '1','cost' => '7','field_allowance' => 'U','parent' => ''),
	array('id' => '504','faction' => 'retribution-of-scyrah','name' => 'Discordia','type' => 'jackbeast','number' => '1','cost' => '10','field_allowance' => 'C','parent' => ''),
	array('id' => '505','faction' => 'retribution-of-scyrah','name' => 'Hypnos','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'C','parent' => ''),
	array('id' => '506','faction' => 'retribution-of-scyrah','name' => 'Heavy Rifle Team','type' => 'warrior','number' => '2','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '507','faction' => 'retribution-of-scyrah','name' => 'House Shyeel Artificer','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '508','faction' => 'retribution-of-scyrah','name' => 'Arcantrik Force Generator','type' => 'warrior','number' => '1','cost' => '10','field_allowance' => '2','parent' => ''),
	array('id' => '509','faction' => 'mercenaries','name' => 'Captain Damiano','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '510','faction' => 'mercenaries','name' => 'Rover','type' => 'jackbeast','number' => '1','cost' => '8','field_allowance' => 'U','parent' => ''),
	array('id' => '511','faction' => 'mercenaries','name' => 'Rocinante','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => 'C','parent' => ''),
	array('id' => '512','faction' => 'circle-orboros','name' => 'Razorwing Griffon','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '513','faction' => 'mercenaries','name' => 'Ogrun Assault Corps','type' => 'warrior','number' => '3, 5','cost' => '6, 9','field_allowance' => '2','parent' => ''),
	array('id' => '514','faction' => 'mercenaries','name' => 'Sylys Wyshnalyrr, the Seeker','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'C','parent' => ''),
	array('id' => '515','faction' => 'mercenaries','name' => 'Ragman','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => 'C','parent' => ''),
	array('id' => '516','faction' => 'cygnar','name' => 'Artificer General Nemo & Storm Chaser Adept Caitlin Finch','type' => 'casterlock','number' => '1','cost' => '-3','field_allowance' => 'C','parent' => ''),
	array('id' => '517','faction' => 'cygnar','name' => 'Stormwall & Lightning Pods','type' => 'jackbeast','number' => '1','cost' => '19','field_allowance' => '2','parent' => ''),
	array('id' => '518','faction' => 'protectorate-of-menoth','name' => 'Intercessor Kreoss','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '519','faction' => 'protectorate-of-menoth','name' => 'Judicator','type' => 'jackbeast','number' => '1','cost' => '18','field_allowance' => '2','parent' => ''),
	array('id' => '520','faction' => 'khador','name' => 'Vladimir Tzepesci, Great Prince of Umbrey','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '521','faction' => 'khador','name' => 'Conquest','type' => 'jackbeast','number' => '1','cost' => '19','field_allowance' => '2','parent' => ''),
	array('id' => '522','faction' => 'retribution-of-scyrah','name' => 'Vyros, Incissar of the Dawnguard','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '523','faction' => 'retribution-of-scyrah','name' => 'Hyperion','type' => 'jackbeast','number' => '1','cost' => '18','field_allowance' => '2','parent' => ''),
	array('id' => '524','faction' => 'mercenaries','name' => 'General Ossrum','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '525','faction' => 'mercenaries','name' => 'Galleon','type' => 'jackbeast','number' => '1','cost' => '18','field_allowance' => '2','parent' => ''),
	array('id' => '526','faction' => 'mercenaries','name' => 'Alexia, Mistress of the Witchfire','type' => 'warrior','number' => '1','cost' => '4','field_allowance' => 'C','parent' => ''),
	array('id' => '527','faction' => 'khador','name' => 'Iron Fang Kovnik','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '533','faction' => 'mercenaries','name' => 'Magnus the Warlord','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '536','faction' => 'mercenaries','name' => 'Kayazy Assassin Underboss','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => '529'),
	array('id' => '535','faction' => 'mercenaries','name' => 'Drake MacBain','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '537','faction' => 'mercenaries','name' => 'Eiryss, Angel of Retribution','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => 'C','parent' => ''),
	array('id' => '538','faction' => 'legion-of-everblight','name' => 'Captain Farilor & Standard','type' => 'warrior','number' => '2','cost' => '3','field_allowance' => 'C','parent' => '449'),
	array('id' => '539','faction' => 'legion-of-everblight','name' => 'Naga Nightlurker','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '540','faction' => 'legion-of-everblight','name' => 'Kallus, Wrath of Everblight','type' => 'casterlock','number' => '1','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '541','faction' => 'legion-of-everblight','name' => 'Lylyth, Reckoning of Everblight','type' => 'casterlock','number' => '1 ','cost' => '-5','field_allowance' => 'C','parent' => ''),
	array('id' => '542','faction' => 'legion-of-everblight','name' => 'Vayl, Consul of Everblight','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '543','faction' => 'legion-of-everblight','name' => 'Afflictor','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '544','faction' => 'legion-of-everblight','name' => 'Archangel','type' => 'jackbeast','number' => '1','cost' => '20','field_allowance' => '2','parent' => ''),
	array('id' => '545','faction' => 'legion-of-everblight','name' => 'Nephilim Bloodseer','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '546','faction' => 'legion-of-everblight','name' => 'Proteus','type' => 'jackbeast','number' => '1','cost' => '11','field_allowance' => 'U','parent' => ''),
	array('id' => '547','faction' => 'legion-of-everblight','name' => 'Throne of Everblight','type' => 'jackbeast','number' => '1','cost' => '9','field_allowance' => '2','parent' => ''),
	array('id' => '548','faction' => 'legion-of-everblight','name' => 'Beast Mistress','type' => 'warrior','number' => '1','cost' => '3','field_allowance' => '2','parent' => ''),
	array('id' => '549','faction' => 'legion-of-everblight','name' => 'Warspear Chieftain','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '550','faction' => 'legion-of-everblight','name' => 'Succubus','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '1','parent' => ''),
	array('id' => '551','faction' => 'trollbloods','name' => 'Sons of Bragg','type' => 'warrior','number' => '3','cost' => '6','field_allowance' => 'C','parent' => ''),
	array('id' => '552','faction' => 'trollbloods','name' => 'Rök','type' => 'jackbeast','number' => '1','cost' => '11','field_allowance' => 'U','parent' => ''),
	array('id' => '553','faction' => 'trollbloods','name' => 'Scattergunner Officer & Standard','type' => 'warrior','number' => '2','cost' => '2','field_allowance' => '1','parent' => '359'),
	array('id' => '554','faction' => 'trollbloods','name' => 'Storm Troll','type' => 'jackbeast','number' => '1','cost' => '5','field_allowance' => 'U','parent' => ''),
	array('id' => '555','faction' => 'trollbloods','name' => 'Grissel Bloodsong, Marshal of the Kriels','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '556','faction' => 'trollbloods','name' => 'Jarl Skuld, Devil of the Thornwood','type' => 'casterlock','number' => '1','cost' => '-6','field_allowance' => 'C','parent' => ''),
	array('id' => '557','faction' => 'trollbloods','name' => 'Hunters Grim','type' => 'casterlock','number' => '1','cost' => '-4','field_allowance' => 'C','parent' => ''),
	array('id' => '558','faction' => 'trollbloods','name' => 'Night Troll','type' => 'jackbeast','number' => '1','cost' => '4','field_allowance' => 'U','parent' => ''),
	array('id' => '559','faction' => 'trollbloods','name' => 'Trollkin Warders','type' => 'warrior','number' => '3,5','cost' => '5,8','field_allowance' => '2','parent' => ''),
	array('id' => '560','faction' => 'trollbloods','name' => 'Trollkin Sorcerer','type' => 'warrior','number' => '1','cost' => '1','field_allowance' => '2','parent' => ''),
	array('id' => '561','faction' => 'trollbloods','name' => 'Fennblade Kithkar','type' => 'warrior','number' => '1','cost' => '2','field_allowance' => '2','parent' => ''),
	array('id' => '562','faction' => 'trollbloods','name' => 'Mountain King','type' => 'jackbeast','number' => '1','cost' => '20','field_allowance' => '2','parent' => ''),
	array('id' => '563','faction' => 'trollbloods','name' => 'Trollkin War Wagon','type' => 'warrior','number' => '1','cost' => '9','field_allowance' => '2','parent' => ''),
);

?>